### ISSUE TITLE
"Show toggle button" setting not respected on new game

### ISSUE THREAD

**Issue by doktorstick** [eduran84/LTN_Tracker#25]
**Error message or bug description**
When the "show toggle button" is deselected under the "player" settings for the mod, and a new game is started, the toggle button is shown in the upper-left. To disable it, you must turn it on, confirm, turn it back off, confirm.

*Edit: Also, it appears reloading a save also defaults to showing it in the upper-left regardless of the setting.*

**To Reproduce**
See above. 

**LTN Tracker version**
0.10.7

**Minor niggle**
This option ("show toggle button") and another ("window height (pixel)") both have periods ending the option labels whereas the general Factorio style is to not have periods ending option labels.

**Comment by eduran84** [comment]
Thanks. I only changed that setting for testing and never noticed. It's fixed in 0.10.8.

> Minor niggle
This option ("show toggle button") and another ("window height (pixel)") both have periods ending the option labels whereas the general Factorio style is to not have periods ending option labels.

Also changed that. Not sure why I put periods on those to settings.
